version: 2

executors:
  my-executor:
    docker:
      - image: circleci/node:erbium
    working_directory: /tmp/my-project
    environment:
      CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>

jobs:
  build:
    executor: my-executor
    steps:
      - run: echo "BUILD -- This is pipeline ID << pipeline.id >>"
      - run: echo $CIRCLE_COMPARE_URL
      - run: mkdir -p workspace
      - run: echo "Hello, world!" > workspace/echo-output
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job.
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: workspace
          # Must be relative path from root
          paths:
            - echo-output

  testing-2:
    executor: my-executor
    steps:
      - run: echo "TESTING-2 -- This is pipeline ID << pipeline.id >>"
      - run: echo $CIRCLE_COMPARE_URL

      - attach_workspace:
        # Must be absolute path or relative path from working_directory
        at: /tmp/workspace

      - run: |
          if [[ `cat /tmp/workspace/echo-output` == "Hello, world!" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

  testing-3:
    executor: my-executor
    steps:
      - run: echo "TESTING-3 -- This is pipeline ID << pipeline.id >>"
      - run: echo $CIRCLE_COMPARE_URL

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
      - testing-2:
          requires:
            - build
          filters:
            branches:
              only: master
      - testing-3:
          type: approval
          requires:
            - testing-2
          filters:
            branches:
              only: staging
