version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:erbium
    working_directory: ~/workspace

jobs:
  build:
    docker:
      - image: circleci/node:erbium
    environment:
      CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
    working_directory: /tmp/my-project
    steps:
      - run: echo "BUILD -- This is pipeline ID << pipeline.id >>"
      - run: echo $CIRCLE_COMPARE_URL

  testing-2:
    docker:
      - image: circleci/node:erbium
    environment:
      CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
    working_directory: /tmp/my-project
    steps:
      - run: echo "TESTING-2 -- This is pipeline ID << pipeline.id >>"
      - run: echo $CIRCLE_COMPARE_URL

  testing-3:
    docker:
      - image: circleci/node:erbium
    environment:
      CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
    working_directory: /tmp/my-project
    steps:
      - run: echo "TESTING-3 -- This is pipeline ID << pipeline.id >>"
      - run: echo $CIRCLE_COMPARE_URL

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
      - testing-2:
          requires:
            - build
          filters:
            branches:
              only: master
      - testing-3:
          requires:
            - testing-2
          filters:
            branches:
              only: staging
